# permissions for end users to view customdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customdeployment-viewer-role
rules:
- apiGroups:
  - crds.k8s.op.asgn
  resources:
  - customdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crds.k8s.op.asgn
  resources:
  - customdeployments/status
  verbs:
  - get
