apiVersion: crds.k8s.op.asgn/v1
kind: CustomDeployment
metadata:
  name: customdeployment-sample
spec:
  # TODO(user): Add fields here
  # host: localhost
  host: 192.168.1.243
  port: 30000
  replicas: 2
  image:
    name: nginx
    tag: latest
